steps:
  # Security scanning step
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=production'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nubemgenesis:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nubemgenesis:latest'
      - '.'
    dir: 'packages/server'

  # Vulnerability scanning
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'images'
      - 'scan'
      - 'gcr.io/$PROJECT_ID/nubemgenesis:$BUILD_ID'
      - '--format=json'
      - '--quiet'

  # Push to registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nubemgenesis:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nubemgenesis:latest'

  # Deploy to Cloud Run with security
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nubemgenesis'
      - '--image=gcr.io/$PROJECT_ID/nubemgenesis:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--port=3000'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=DATABASE_HOST=DATABASE_HOST:latest,DATABASE_NAME=DATABASE_NAME:latest,DATABASE_USER=DATABASE_USER:latest,DATABASE_PASSWORD=DATABASE_PASSWORD:latest,DATABASE_PORT=DATABASE_PORT:latest,DATABASE_TYPE=DATABASE_TYPE:latest,DATABASE_SSL=DATABASE_SSL:latest,FLOWISE_USERNAME=FLOWISE_USERNAME:latest,FLOWISE_PASSWORD=FLOWISE_PASSWORD:latest,FLOWISE_SECRETKEY_OVERWRITE=FLOWISE_SECRETKEY_OVERWRITE:latest'
      - '--service-account=nubemgenesis-sa@$PROJECT_ID.iam.gserviceaccount.com'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'