steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/nubemgenesis",
        "-f",
        "Dockerfile.fix-port",
        ".",
      ]
images:
  - gcr.io/$PROJECT_ID/nubemgenesis