steps:
  # Step 1: Build the image with authentication system
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.production'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nubemgenesis-auth:$BUILD_ID'
      - '-t' 
      - 'gcr.io/$PROJECT_ID/nubemgenesis-auth:latest'
      - '.'
    timeout: '1800s'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/nubemgenesis-auth'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nubemgenesis'
      - '--image=gcr.io/$PROJECT_ID/nubemgenesis-auth:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=PORT=3000'
      - '--set-env-vars=DATABASE_TYPE=sqlite'
      - '--set-env-vars=LOG_LEVEL=info'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'