steps:
  # Construir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/app:latest', '.']

  # Publicar la imagen en Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/app:latest']

timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_8'
