# Complete orchestrator deployment with all features
steps:
  # Build orchestrator image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.orchestrator-complete',
      '-t', 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-v2:latest',
      '.'
    ]
    id: 'build-orchestrator'

  # Push image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-v2:latest']
    waitFor: ['build-orchestrator']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'nubemgenesis-orchestrator-v2',
      '--image', 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-v2:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '8Gi',
      '--cpu', '4',
      '--timeout', '600',
      '--max-instances', '20',
      '--min-instances', '1',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-env-vars', 'LITELLM_PROXY_URL=https://litellm-proxy.run.app',
      '--set-env-vars', 'ENABLE_EVALUATION_SCHEDULER=true',
      '--set-env-vars', 'ENABLE_CAPABILITY_WATCHER=true',
      '--set-env-vars', 'SECURITY_LEVEL=high',
      '--set-env-vars', 'OBSERVABILITY_ENABLED=true',
      '--set-env-vars', 'OPENAI_API_KEY=placeholder',
      '--set-env-vars', 'ANTHROPIC_API_KEY=placeholder'
    ]

  # Deploy LiteLLM proxy separately
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.litellm',
      '-t', 'gcr.io/$PROJECT_ID/litellm-proxy:latest',
      '.'
    ]
    id: 'build-litellm'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/litellm-proxy:latest']
    waitFor: ['build-litellm']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'litellm-proxy',
      '--image', 'gcr.io/$PROJECT_ID/litellm-proxy:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '1',
      '--port', '8000',
      '--set-env-vars', 'LITELLM_MODE=proxy'
    ]

# Build configuration
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Images
images:
  - 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-v2:latest'
  - 'gcr.io/$PROJECT_ID/litellm-proxy:latest'