steps:
  # Construir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/app:latest', '.']

  # Publicar la imagen en Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/app:latest']

  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nubemgenesis'
      - '--image'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/app:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'nubemgenesis-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'DATABASE_TYPE=DATABASE_TYPE:latest,DATABASE_HOST=DATABASE_HOST:latest,DATABASE_PORT=DATABASE_PORT:latest,DATABASE_NAME=DATABASE_NAME:latest,DATABASE_USER=DATABASE_USER:latest,DATABASE_PASSWORD=DATABASE_PASSWORD:latest,DATABASE_SSL=DATABASE_SSL:latest,REDIS_HOST=REDIS_HOST:latest,REDIS_PORT=REDIS_PORT:latest,REDIS_USERNAME=REDIS_USERNAME:latest,REDIS_PASSWORD=REDIS_PASSWORD:latest,REDIS_TLS=REDIS_TLS:latest,FLOWISE_USERNAME=FLOWISE_USERNAME:latest,FLOWISE_PASSWORD=FLOWISE_PASSWORD:latest,FLOWISE_SECRETKEY_OVERWRITE=FLOWISE_SECRETKEY_OVERWRITE:latest,JWT_SECRET=JWT_SECRET:latest,LOG_LEVEL=LOG_LEVEL:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,MISTRAL_API_KEY=MISTRAL_API_KEY:latest,DEEPSEEK_API_KEY=DEEPSEEK_API_KEY:latest,CORS_ORIGINS=CORS_ORIGINS:latest,IFRAME_ORIGINS=IFRAME_ORIGINS:latest,FLOWISE_FILE_SIZE_LIMIT=FLOWISE_FILE_SIZE_LIMIT:latest'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:us-central1:nubemgenesis-db'
      - '--min-instances'
      - '1'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'

  # Configurar el dominio personalizado
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      -  < /dev/null | 
        # Verificar el servicio
        gcloud run services describe nubemgenesis --region=us-central1
        
        # Configurar dominio personalizado
        echo "Configurando dominio personalizado nubemgenesis.ai..."
        gcloud beta run domain-mappings create \
          --service=nubemgenesis \
          --domain=nubemgenesis.ai \
          --region=us-central1

        # Obtener registros DNS necesarios
        echo "Mostrando registros DNS necesarios para configurar el dominio..."
        gcloud beta run domain-mappings describe \
          --domain=nubemgenesis.ai \
          --region=us-central1 \
          --format="value(resourceRecords)"

timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_8'
