steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-production:$COMMIT_SHA', '-f', 'Dockerfile.orchestrator-production', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-production:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nubemgenesis-orchestrator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-production:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '1'
      - '--service-account'
      - 'nubemgenesis-orchestrator@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,GCP_LOCATION=us-central1'

images:
  - 'gcr.io/$PROJECT_ID/nubemgenesis-orchestrator-production:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY