steps:
  # Build the Docker image with complete monorepo
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/nubemgenesis:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/nubemgenesis:production'
      - '-f'
      - 'Dockerfile.complete-build'
      - '.'
    timeout: 1800s

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/nubemgenesis'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nubemgenesis'
      - '--image'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/nubemgenesis:production'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,FLOWISE_USERNAME=admin,FLOWISE_PASSWORD=${_FLOWISE_PASSWORD}'
      - '--set-secrets'
      - 'DATABASE_PASSWORD=nubemgenesis-db-password:latest,PASSPHRASE=nubemgenesis-passphrase:latest,JWT_SECRET=nubemgenesis-jwt-secret:latest'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/nubemgenesis:latest'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/nubemgenesis/nubemgenesis:production'

timeout: 2400s

options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FLOWISE_PASSWORD: 'NubemGen2025!'