version: '3.8'

services:
  litellm:
    image: ghcr.io/berriai/litellm:latest
    container_name: nubemgenesis-litellm
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-sk-nubemgenesis-master-key}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/litellm
      - REDIS_URL=redis://redis:6379
      # Model API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      # Observability
      - OTEL_ENDPOINT=${OTEL_ENDPOINT:-http://otel-collector:4318}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    command: --config /app/config.yaml --port 4000 --num_workers 4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
      - redis
    networks:
      - nubemgenesis-network

  postgres:
    image: postgres:15-alpine
    container_name: nubemgenesis-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-nubemgenesis}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nubemgenesis123}
      - POSTGRES_DB=nubemgenesis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nubemgenesis-network

  redis:
    image: redis:7-alpine
    container_name: nubemgenesis-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - nubemgenesis-network

  # Optional: OpenTelemetry Collector for observability
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: nubemgenesis-otel
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"   # OTLP HTTP
      - "4317:4317"   # OTLP gRPC
      - "8888:8888"   # Prometheus metrics
    networks:
      - nubemgenesis-network

volumes:
  postgres-data:
  redis-data:

networks:
  nubemgenesis-network:
    driver: bridge